# Generated by Django 5.2.7 on 2026-09-16 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "accounts",
            "0005_profile_last_login_date_profile_points_profile_role_and_more",
        ),
        ("words", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("audio", "🎧 Аудирование"),
                            ("translate", "📖 Перевод"),
                            ("speak", "🎙️ Произношение"),
                            ("build", "🧩 Собери слово"),
                            ("pairs", "🔗 Найди пару"),
                            ("gap", "📝 Вставь пропуск"),
                            ("dialog", "💬 Диалог"),
                            ("crossword", "🧩 Кроссворд"),
                            ("quick", "⏱️ Быстрый раунд"),
                            ("creative", "🎨 Творческое"),
                        ],
                        max_length=32,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Баллы"
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, verbose_name="Настройки"),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocks",
                        to="words.word",
                        verbose_name="Слова",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
                "ordering": ("order_index",),
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                ("answer", models.TextField(blank=True, verbose_name="Ответ")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Верно"),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Баллы"
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Время (сек)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lessons.block",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        verbose_name="Публичный (для самостоятельного обучения)",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        unique=True,
                        verbose_name="Код урока",
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Лимит времени (мин)"
                    ),
                ),
                (
                    "leaderboard_on",
                    models.BooleanField(
                        default=True, verbose_name="Показывать лидерборд"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="accounts.classgroup",
                        verbose_name="Класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="block",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="lessons.lesson",
            ),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Итоговый балл"
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        default=False, verbose_name="Завершён"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по уроку",
                "verbose_name_plural": "Прогресс по урокам",
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
