# Generated by Django 5.2.7 on 2026-09-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[
                    ("audio", "🎧 Аудирование"),
                    ("translate", "📖 Перевод"),
                    ("build", "🧩 Собери слово"),
                    ("pairs", "🔗 Найди пару"),
                    ("quick", "⏱️ Быстрый раунд"),
                    ("gap", "📝 Вставь пропуск"),
                ],
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
