# Generated by Django 5.2.7 on 2026-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_block_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="allow_retry",
            field=models.BooleanField(
                default=True,
                help_text="Если выключено, ученик может пройти урок только один раз",
                verbose_name="Разрешить повторное прохождение",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_competition",
            field=models.BooleanField(
                default=False, verbose_name="Соревнование"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичный"),
        ),
    ]
