# Generated by Django 5.2.7 on 2026-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_lesson_allow_retry_lesson_is_competition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="show_answers_after",
            field=models.BooleanField(
                default=False,
                help_text="Ученик увидит свои ответы и правильные после прохождения",
                verbose_name="Показывать правильные ответы после завершения",
            ),
        ),
    ]
