# Generated by Django 5.2.7 on 2026-09-16 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_chatmessage_options_alter_notification_options",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_login_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="Очки"),
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Учитель"),
                    ("student", "Ученик"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=16,
                verbose_name="Роль",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="streak",
            field=models.PositiveIntegerField(default=0, verbose_name="Стрик"),
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Название"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Класс",
                "verbose_name_plural": "Классы",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="accounts.classgroup",
                verbose_name="Класс",
            ),
        ),
    ]
