# Generated by Django 5.2.7 on 2026-09-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "tatar",
                    models.CharField(
                        max_length=128, verbose_name="Татарское слово"
                    ),
                ),
                (
                    "russian",
                    models.CharField(
                        max_length=128, verbose_name="Русский перевод"
                    ),
                ),
                (
                    "transcription",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Транскрипция"
                    ),
                ),
                (
                    "example_tt",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Пример (татарский)",
                    ),
                ),
                (
                    "example_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Пример (русский)",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("family", "Семья"),
                            ("food", "Еда"),
                            ("animals", "Животные"),
                            ("school", "Школа"),
                            ("nature", "Природа"),
                            ("city", "Город"),
                            ("body", "Тело"),
                            ("colors", "Цвета"),
                            ("numbers", "Числа"),
                            ("verbs", "Глаголы"),
                        ],
                        default="family",
                        max_length=32,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Начальный"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="beginner",
                        max_length=32,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на аудио"
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово",
                "verbose_name_plural": "Слова",
                "ordering": ("tatar",),
            },
        ),
        migrations.CreateModel(
            name="DailyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_entries",
                        to="words.word",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово дня",
                "verbose_name_plural": "Слова дня",
                "ordering": ("-date",),
            },
        ),
    ]
