# Generated by Django 5.2.7 on 2026-09-18 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Начало")),
                ("end_time", models.DateTimeField(verbose_name="Окончание")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Если выключено — соревнование скрыто от пользователей",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
                "ordering": ("-start_time",),
            },
        ),
        migrations.CreateModel(
            name="CompetitionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "statement",
                    models.TextField(
                        help_text="Текст задания, который видит участник",
                        verbose_name="Условие",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовый ответ"),
                            ("choice", "Выбор варианта"),
                        ],
                        default="text",
                        max_length=32,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        max_length=255, verbose_name="Правильный ответ"
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Варианты ответа (для choice)",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Баллы"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Максимум попыток"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача соревнования",
                "verbose_name_plural": "Задачи соревнования",
                "ordering": ("order_index", "id"),
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Верно"),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Баллы"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Номер попытки"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="competitions.competitiontask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Посылка",
                "verbose_name_plural": "Посылки",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CompetitionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Баллы"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник соревнования",
                "verbose_name_plural": "Участники соревнований",
                "ordering": ("-score", "created_at"),
                "unique_together": {("competition", "user")},
            },
        ),
    ]
