# Generated by Django 5.2.7 on 2026-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitiontask",
            name="build_hint",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Подсказка"
            ),
        ),
        migrations.AddField(
            model_name="competitiontask",
            name="build_word",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Слово для сборки"
            ),
        ),
        migrations.AddField(
            model_name="competitiontask",
            name="pairs",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Пары"
            ),
        ),
        migrations.AddField(
            model_name="competitiontask",
            name="voice_text",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Текст для произнесения",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="competitiontask",
            name="correct_answer",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Правильный ответ"
            ),
        ),
        migrations.AlterField(
            model_name="competitiontask",
            name="options",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Варианты"
            ),
        ),
        migrations.AlterField(
            model_name="competitiontask",
            name="statement",
            field=models.TextField(verbose_name="Условие"),
        ),
        migrations.AlterField(
            model_name="competitiontask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("text", "📝 Текстовый ответ"),
                    ("choice", "🔘 Один вариант"),
                    ("multiple_choice", "☑️ Несколько вариантов"),
                    ("build", "🧩 Собери слово"),
                    ("pairs", "🔗 Найди пару"),
                    ("voice", "🎙️ Голосовой перевод"),
                ],
                default="text",
                max_length=32,
                verbose_name="Тип",
            ),
        ),
    ]
